### ISSUE TITLE
go get github.com/gvalkov/golang-evdev fails

### ISSUE THREAD

**Issue by jeromesancho** [gvalkov/golang-evdev#10]
When I run the command :

go get -v "github.com/gvalkov/golang-evdev"
github.com/gvalkov/golang-evdev (download)
github.com/gvalkov/golang-evdev
# github.com/gvalkov/golang-evdev
../../../../../gvalkov/golang-evdev/cdefs.go:4:26: fatal error: linux/input.h: No such file or directory
  #include <linux/input.h>
                          ^
compilation terminated.

I run the command from a docker container :
FROM golang:1.11.0-alpine3.8 as builder
RUN apk add -U alpine-sdk git python
ENV GOARCH=arm64

I tried cross compiling:
 GOARCH=arm64 go build -v
github.com/Max2Inc/IES-Services/golang-evdev-master
# github.com/Max2Inc/IES-Services/golang-evdev-master
./device.go:132:9: undefined: ioctl
./device.go:132:38: undefined: EVIOCGBIT
./device.go:142:4: undefined: ioctl
./device.go:142:33: undefined: EVIOCGBIT
./device.go:164:15: undefined: MAX_NAME_SIZE
./device.go:165:15: undefined: MAX_NAME_SIZE
./device.go:167:9: undefined: ioctl
./device.go:167:38: undefined: EVIOCGID
./device.go:172:2: undefined: ioctl
./device.go:323:26: undefined: MAX_NAME_SIZE
./device.go:172:2: too many errors

with the following config 
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jerome/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jerome/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jerome/Documents/Go Examples/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build261697354=/tmp/go-build -gno-record-gcc-switches"

**Comment by jeromesancho** [comment]
Solved by using a debian image

**Comment by gvalkov** [comment]
Hi. `apk add linux-headers` fixes it for me on alpine.
